{"version":3,"sources":["../../app-src/util/ApplicationException.js"],"names":["ApplicationException","Error","constructor","msg","name","exception","isApplicationException","err","Object","getPrototypeOf","getExceptionMessage","message","console","log"],"mappings":";;;;;;AAAO,YAAMA,oBAAN,SAAmCC,KAAnC,CAAyC;AAC9CC,oBAAYC,MAAM,EAAlB,EAAsB;AACpB,gBAAMA,GAAN;;AAEA,eAAKC,IAAL,GAAY,KAAKF,WAAL,CAAiBE,IAA7B;AACD;AAL6C;;;;AAQhD,YAAMC,YAAYL,oBAAlB;;AAEO,eAASM,sBAAT,CAAgCC,GAAhC,EAAqC;AAC1C,eAAOA,eAAeF,SAAf,IACLG,OAAOC,cAAP,CAAsBF,GAAtB,aAAsCF,SADxC;AAED;;;;AAEM,eAASK,mBAAT,CAA6BH,GAA7B,EAAkC;AACvC,YAAID,uBAAuBC,GAAvB,CAAJ,EAAiC;AAC/B,iBAAOA,IAAII,OAAX;AACD,SAFD,MAEO;AACLC,kBAAQC,GAAR,CAAYN,GAAZ;;AAEA,iBAAO,4BAAP;AACD;AACF","file":"ApplicationException.js","sourcesContent":["export class ApplicationException extends Error {\n  constructor(msg = '') {\n    super(msg);\n    \n    this.name = this.constructor.name;\n  }\n}\n\nconst exception = ApplicationException;\n\nexport function isApplicationException(err) {\n  return err instanceof exception ||\n    Object.getPrototypeOf(err) instanceof exception\n}\n\nexport function getExceptionMessage(err) {\n  if (isApplicationException(err)) {\n    return err.message;\n  } else {\n    console.log(err);\n\n    return 'An unexpected error occurs';\n  }\n}\n"]}